# Generated by Django 3.2.6 on 2021-08-18 17:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=django.contrib.auth.models.User),
        ),
    ]
