# Generated by Django 3.2.6 on 2021-08-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patientinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
