# Generated by Django 3.2.6 on 2021-10-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_bookappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
