# Generated by Django 3.2.6 on 2021-10-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_bookappointment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
