# Generated by Django 3.2.6 on 2021-10-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_bookappointment_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
