# Generated by Django 3.2.6 on 2021-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_bookappointment_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='checker',
            field=models.IntegerField(default=1),
        ),
    ]
