# Generated by Django 3.2.6 on 2021-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_bookappointment_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='checker',
            field=models.IntegerField(default=0),
        ),
    ]
