# Generated by Django 3.2.6 on 2021-08-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctorspec_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorspec',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctorinfo'),
        ),
    ]
