# Generated by Django 3.2.6 on 2021-08-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorspec_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_id',
        ),
    ]
