# Generated by Django 3.2.6 on 2021-08-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_doctorinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspec',
            name='doctor_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctorinfo'),
        ),
    ]
