# Generated by Django 3.2.6 on 2021-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_appointment_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ManyToManyField(null=True, to='doctor.DoctorInfo'),
        ),
    ]
