# Generated by Django 3.2.6 on 2021-10-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20211018_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='enrolled_patient',
            field=models.IntegerField(default=0),
        ),
    ]
